In [1]:
!pip install Transformers

     |████████████████████████████████| 3.5 MB 5.4 MB/s 
     |████████████████████████████████| 596 kB 47.9 MB/s 
     |████████████████████████████████| 67 kB 4.0 MB/s 
     |████████████████████████████████| 895 kB 40.7 MB/s 
     |████████████████████████████████| 6.8 MB 41.4 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [7]:
from transformers import BertTokenizer, BertForMaskedLM
import torch

In [14]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForMaskedLM.from_pretrained('bert-base-uncased') # what is bert base uncased 
text = ("After Abraham Lincoln won the November 1860 presidential election on an "
        "anti-slavery platform, an initial seven slave stated declared their"
        "secession from the country to form the Confederacy. War broke out in"
        "April 1861 when secessionist forces attacked Fort Sumter in South "
        "Carolina, just over a month after Lincoln's inauguration.")

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForMaskedLM: ['cls.seq_relationship.bias', 'cls.seq_relationship.weight']
- This IS expected if you are initializing BertForMaskedLM from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForMaskedLM from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [15]:
inputs = tokenizer(text, return_tensors = 'pt')
inputs.keys() #what tensors we return from that 

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [16]:
#focusing on input_ids on this video. 
inputs.input_ids

tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  3090,  4161, 17156, 26005, 28231,  2013,  1996,  2406,  2000,
          2433,  1996, 18179,  1012,  2162,  3631,  2041, 27118, 18098,  4014,
          6863,  2043, 22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,
          2148,  3792,  1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,
          1055, 17331,  1012,   102]])

In [17]:
#create out target labels 
inputs['labels'] = inputs.input_ids.detach().clone()  #copy of inputs ids of tensor 

In [18]:
inputs

{'input_ids': tensor([[  101,  2044,  8181,  5367,  2180,  1996,  2281,  7313,  4883,  2602,
          2006,  2019,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  3090,  4161, 17156, 26005, 28231,  2013,  1996,  2406,  2000,
          2433,  1996, 18179,  1012,  2162,  3631,  2041, 27118, 18098,  4014,
          6863,  2043, 22965,  2923,  2749,  4457,  3481,  7680,  3334,  1999,
          2148,  3792,  1010,  2074,  2058,  1037,  3204,  2044,  5367,  1005,
          1055, 17331,  1012,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1

In [19]:
rand = torch.rand(inputs.input_ids.shape)
rand.shape

torch.Size([1, 64])

In [20]:
rand

tensor([[0.5453, 0.2935, 0.0346, 0.1767, 0.5329, 0.7101, 0.6116, 0.8584, 0.1083,
         0.9637, 0.1599, 0.0472, 0.3483, 0.6065, 0.7045, 0.6386, 0.7879, 0.9072,
         0.2833, 0.9170, 0.8301, 0.6008, 0.5725, 0.1849, 0.0766, 0.6977, 0.7745,
         0.1887, 0.4758, 0.6015, 0.6149, 0.1350, 0.0524, 0.3502, 0.3041, 0.3426,
         0.4512, 0.5855, 0.9040, 0.5208, 0.8751, 0.5783, 0.6643, 0.9153, 0.8671,
         0.9621, 0.5948, 0.0055, 0.4799, 0.8229, 0.0144, 0.2606, 0.2473, 0.0509,
         0.4635, 0.6679, 0.0914, 0.0261, 0.8336, 0.0867, 0.1584, 0.4366, 0.2853,
         0.7613]])

In [23]:
mask_arr = (rand < 0.15) * (inputs.input_ids != 101) * (inputs.input_ids != 102)
mask_arr

tensor([[False, False,  True, False, False, False, False, False,  True, False,
         False,  True, False, False, False, False, False, False, False, False,
         False, False, False, False,  True, False, False, False, False, False,
         False,  True,  True, False, False, False, False, False, False, False,
         False, False, False, False, False, False, False,  True, False, False,
          True, False, False,  True, False, False,  True,  True, False,  True,
         False, False, False, False]])

In [22]:
#don't want to mask special tokens (first & last)
(inputs.input_ids != 101) * (inputs.input_ids != 102)

tensor([[False,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True,  True,  True,  True,  True,  True,  True,  True,
          True,  True,  True, False]])

In [29]:
selection = torch.flatten(mask_arr[0].nonzero()).tolist()
selection

[2, 8, 11, 24, 31, 32, 47, 50, 53, 56, 57, 59]

In [30]:
inputs.input_ids[0, selection] = 103
inputs.input_ids

tensor([[  101,  2044,   103,  5367,  2180,  1996,  2281,  7313,   103,  2602,
          2006,   103,  3424,  1011,  8864,  4132,  1010,  2019,  3988,  2698,
          6658,  3090,  4161, 17156,   103, 28231,  2013,  1996,  2406,  2000,
          2433,   103,   103,  1012,  2162,  3631,  2041, 27118, 18098,  4014,
          6863,  2043, 22965,  2923,  2749,  4457,  3481,   103,  3334,  1999,
           103,  3792,  1010,   103,  2058,  1037,   103,   103,  5367,   103,
          1055, 17331,  1012,   102]])

In [31]:
outputs = model(**inputs)
outputs.keys()

odict_keys(['loss', 'logits'])

In [32]:
outputs.loss

tensor(1.2140, grad_fn=<NllLossBackward0>)